movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:m_id>/',views.detail,name='detail'),
    path('add/',views.add_mov,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250,null=True)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from . models import movie

class movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import movieform
from . models import movie
# Create your views here.
def index(request):
    mov=movie.objects.all()
    context={
        'movie_list':mov
    }
    return render(request,"index.html", context)

def detail(request,m_id):
    move=movie.objects.get(id=m_id)
    return render(request,'detail.html',{'move':move})

def add_mov(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        move=movie(name=name, desc=desc, year=year, img=img)
        move.save()
    return render(request,"addmov.html")
def update(request,id):
    move=movie.objects.get(id=id)
    form=movieform(request.POST or None, request.FILES, instance=move)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form, 'move':move})

def delete(request,id):
    if request.method=='POST':
        move=movie.objects.get(id=id)
        move.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/addmov.html
{% extends 'base.html' %}
{% block body %}
<head>
    <meta charset="UTF-8">
    <title>Add Movies</title>
</head>
<body>
<h2 class="pb-5 pt-3" style="text-align: center"> Add Movies</h2>
<form class="text-center" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Movie Name">
    <input type="text" name="desc" placeholder="Enter Movie Description">
    <input type="text" name="year" placeholder="Enter Movie Year">
    <input type="file" name="img" placeholder="Upload Image">
    <input type="submit" placeholder="Add Film">
</form>
<div class="text-center pt-5">
 <a href="{% url 'movieapp:index' %}" class="btn btn-primary ">Homepage</a>
</body>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MovieApp</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="background-color: #F1F2F4">
<!-- Image and text -->
<nav class="navbar navbar-dark" style="background-color: #0E263E; height: 78px;">
  <a class="navbar-brand" href="{% url 'movieapp:index' %}">
    StarGo | RoyCo
  </a>
</nav>
<!--<h2>These are the movies on my list!</h2>-->
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Movie</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    Delete This Film?
<input type="submit" placeholder="Yes, I'd like to delete.">
</form>
</body>
</html>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="background-color: #04356A; padding:100px 140px;">
    <div class="row">
        <div class="col-md-6 p-2"  style="background-color: #F1F2F4;">
            <img src="{{move.img.url}}" width="250" height="300">
        </div>

        <div class="col-md-6 p-4" style="background-color: #5079F2; text-align: center; ">
        <div class="p-2 my-4 m" style="background-color: #0E263E; border-radius: 10px">
        <h5>Movie Description</h5>
        <h3>{{move.name}}</h3>
        <h6>{{move.desc}}</h6>
        <h6>{{move.year}}</h6>
        <a class="btn btn-dark" href="{% url 'movieapp:update' move.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'movieapp:delete' move.id %}">Delete</a>
        </div>
        </div>
    </div>
</div>

{% endblock %}

movieproject/templates/edit.html
<head>
    <meta charset="UTF-8">
    <title>Update Movies</title>
</head>
{% extends 'base.html' %}
{% block body %}
<body>
<div class="m-4 p-2">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
<input type="submit">
</form>
</div>
</body>
{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container" style="background-color: #F1F2F4">
    <div class="header p-2" style="background-color: #04356A; color: white; text-align: center;">Movie Library</div>
    {% if not movie_list %}
    <div>
    <div class="text-center">
        <br>
        <h1 class="text-center tiitle">Your Movie Library is currently Empty!</h1><br>
        <p class="text-center">Please <a href="{% url 'movieapp:add' %}">Click Here</a> to Add Movies! </p>
    </div>
    </div>
    {% else %}
     <div class="row">
         {% for i in movie_list %}
         <div class="col-md-3 p-3" style="">
             <div class="card" style="width: 16rem;">
              <img src="{{i.img.url}}" class="card-img-top" alt="" height="300px">
              <div class="card-body">
                <h4 class="card-title">{{i.name}}</h4>
                <p class="card-text">{{i.desc}}</p>
                <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View Details</a>
              </div>
            </div>
         </div>
         {% endfor %}
     </div>
    <div class="header p-2" style="background-color: 04356A; color: white; text-align: center;">Want to Add more Movies?
    <a href="{% url 'movieapp:add' %}" class="btn btn-secondary" >Click Here</a>
    </div>
    {% endif %}
</div>

{% endblock %}